# Generated by Django 4.1.7 on 2023-02-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_crest_name_id_alter_image_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crest',
            name='name_id',
            field=models.ForeignKey(db_column='name_id', on_delete=django.db.models.deletion.CASCADE, related_name='crests', to='api.family'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_id',
            field=models.ForeignKey(db_column='name_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.family'),
        ),
    ]
